default:
  image: python:3.9.1


stages:
    - test1
    - test2
    - test3
    - test4
    - test5

before_script:
    - sudo apt-get update
    - sudo apt-get install software-properties-common -y
    - sudo apt-get install default-jre -y
    - sudo apt-get install curl -y
    - sudo apt-get install gzip -y
    - sudo apt-get install xvfb -y
    - curl -o allure-2.13.9.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.tgz
    - sudo tar -zxvf allure-2.13.9.tgz -C /opt/
    - sudo ln -s /opt/allure-2.13.9/bin/allure /usr/bin/allure
    - sudo pip install -r requirements.txt

# ApiTest:
#   stage: test1
#   tags:
#     - python
#   script:
#     - python run.py api test
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# KycTest:
#   stage: test4
#   tags:
#     - python
#   script:
#     - python run.py kyc test
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# CabinetTest:
#   stage: test2
#   tags:
#     - python
#   script:
#     - python run.py cabinet test
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# ConnectTest:
#   stage: test3
#   tags:
#     - python
#   script:
#     - python run.py connect test
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week

WebTest:
  stage: test5
  image: selenium/standalone-chrome
  tags:
    - python
  script:
    - python run.py web test
  artifacts:
    paths:
      - Reports
    expire_in: 1 week
