default:
  image: python:3.9.1

before_script:
    - apt-get update
    - apt-get install software-properties-common -y
    - apt-get install default-jre -y
    - apt-get install curl -y
    - apt-get install gzip -y
    - curl -o allure-2.13.9.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.tgz
    - tar -zxvf allure-2.13.9.tgz -C /opt/
    - ln -s /opt/allure-2.13.9/bin/allure /usr/bin/allure
    - pip install -r requirements.txt

ApiTest:
  tags:
    - python
  script:
    - python run.py api test
  artifacts:
    paths:
      - Reports
    expire_in: 1 week

KycTest:
  tags:
    - python
  script:
    - python run.py kyc test
  artifacts:
    paths:
      - Reports
    expire_in: 1 week

CabinetTest:
  tags:
    - python
  script:
    - python run.py cabinet test
  artifacts:
    paths:
      - Reports
    expire_in: 1 week