default:
  image: python:3.9.1


stages:
    - test1
    - test2
    - test3
    - test4
    - test5
    - test6
    - test7
    - test8

before_script:
    - apt-get update
    - apt-get install software-properties-common -y
    - apt-get install default-jre -y
    - apt-get install curl -y
    - apt-get install gzip -y
    - apt-get install xvfb -y
    - curl -o allure-2.13.9.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.tgz
    - tar -zxvf allure-2.13.9.tgz -C /opt/
    - ln -s /opt/allure-2.13.9/bin/allure /usr/bin/allure
    - pip install -r requirements.txt

# Api Test:
#   stage: test5
#   tags:
#     - python
#   script:
#     - python run.py api en_US
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# Cabital Pay Test:
#   stage: test2
#   tags:
#     - python
#   script:
#     - python run.py pay en_US
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# Cabinet Test:
#   stage: test3
#   tags:
#     - python
#   script:
#     - python run.py cabinet en_US
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# Bybit Test:
#   stage: test4
#   tags:
#     - python
#   script:
#     - python run.py bybit en_US
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# Accounting Test:
#   stage: test1
#   tags:
#     - python
#   script:
#     - python run.py accounting en_US
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# Infinni Games Test:
#   stage: test6
#   tags:
#     - python
#   script:
#     - python run.py infinni en_US
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# Kyc Test:
#   stage: test7
#   tags:
#     - python
#   script:
#     - python run.py kyc test
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# Kyc Test（sanbox）:
#   stage: test7
#   tags:
#     - python
#   script:
#     - python run.py kyc sanbox
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week

Cabital Connect Test:
  stage: test8
  tags:
    - python
  script:
    - python run.py connect bybit
  artifacts:
    paths:
      - Reports
    expire_in: 1 week

Cabital Connect Test:
  stage: test8
  tags:
    - python
  script:
    - python run.py connect gate
  artifacts:
    paths:
      - Reports
    expire_in: 1 week