before_script:
  - apt-get update
  - apt-get install software-properties-common -y
  - apt-get install default-jre -y
  - apt-get install default-jdk -y
  - apt-get install curl -y
  - apt-get install gzip -y
  - curl -o allure-2.13.9.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.tgz
  - tar -zxvf allure-2.13.9.tgz -C /opt/
  - ln -s /opt/allure-2.13.9/bin/allure /usr/bin/allure
  - pip install --upgrade pip
  - pip install -r requirements.txt

apiTest:
  stage: test
  tags:
    - python
  script:
    - python run.py
  artifacts:
    paths:
      - Reports
    expire_in: 1 week


