default:
  image: python:3.9.1


stages:
    - test1
    - test2
    - test3
    - test4
    - test5
    - test6

before_script:
    - apt-get update
    - apt-get install software-properties-common -y
    - apt-get install default-jre -y
    - apt-get install curl -y
    - apt-get install gzip -y
    - apt-get install xvfb -y
    - curl -o allure-2.13.9.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.tgz
    - tar -zxvf allure-2.13.9.tgz -C /opt/
    - ln -s /opt/allure-2.13.9/bin/allure /usr/bin/allure
    - pip install -r requirements.txt

ApiTest:
  stage: test1
  tags:
    - python
  script:
    - python run.py api en_US
  artifacts:
    paths:
      - Reports
    expire_in: 1 week

CabinetTest:
  stage: test2
  tags:
    - python
  script:
    - python run.py cabinet en_US
  artifacts:
    paths:
      - Reports
    expire_in: 1 week

ConnectTest:
  stage: test3
  tags:
    - python
  script:
    - python run.py connect en_US
  artifacts:
    paths:
      - Reports
    expire_in: 1 week

AccountingTest:
  stage: test4
  tags:
    - python
  script:
    - python run.py accounting en_US
  artifacts:
    paths:
      - Reports
    expire_in: 1 week

Infinni Games Test:
  stage: test5
  tags:
    - python
  script:
    - python run.py infinni en_US
  artifacts:
    paths:
      - Reports
    expire_in: 1 week

# KycTest:
#   stage: test6
#   tags:
#     - python
#   script:
#     - python run.py kyc test
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
