default:
  image: python:3.9.1


stages:
    - test1
    - test2
    - test3
    - test4
    - test5

before_script:
    - apt-get update
    - apt-get install software-properties-common -y
    - apt-get install default-jre -y
    - apt-get install curl -y
    - apt-get install gzip -y
    - apt-get install xvfb -y
    - curl -o allure-2.13.9.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.13.9/allure-2.13.9.tgz
    - tar -zxvf allure-2.13.9.tgz -C /opt/
    - ln -s /opt/allure-2.13.9/bin/allure /usr/bin/allure
    - pip install -r requirements.txt
    - Xvfb :99 -ac &

# ApiTest:
#   stage: test1
#   tags:
#     - python
#   script:
#     - python run.py api test
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# KycTest:
#   stage: test4
#   tags:
#     - python
#   script:
#     - python run.py kyc test
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# CabinetTest:
#   stage: test2
#   tags:
#     - python
#   script:
#     - python run.py cabinet test
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
#
# ConnectTest:
#   stage: test3
#   tags:
#     - python
#   script:
#     - python run.py connect test
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
selenium-hub:
    image: selenium/hub:4.1.2-20220208
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
 
WebTest:
  stage: test5
  image: selenium/node-chrome:4.1.2-20220208
  shm_size: 2gb
  depends_on:
    - selenium-hub
  environment:
    - SE_EVENT_BUS_HOST=selenium-hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  ports:
    - "6900:5900"

#   tags:
#     - python
#   script:
#     - python run.py web test
#   artifacts:
#     paths:
#       - Reports
#     expire_in: 1 week
